Patch fs-ext with
Travis builds fails on Node.js stable with:

```
/home/travis/build/mikesamuel/attack-review-testbed/node_modules/fs-ext/fs-ext.js:142
    constants[key] = binding[key];
                   ^
TypeError: Cannot add property SEEK_SET, object is not extensible
```

This applies the fix from https://github.com/baudehlo/node-fs-ext/issues/76
on postinstall so we don't have to wait for upstream.